clear all, close all

disp('Make sure the right data is saved in the lazy mat file')

r = RGCclass(0);
r.lazyLoad();

% Do a blind clustering using all features

% Do a blind clustering using the selected feature subsets

featSetAll = {'ALL', ...
              setdiff(r.allFeatureNames, {'meanAxonThickness','dendriticVAChT'})};

featSet1 = { 'DD-SA-DF-BSD', ...
             { 'dendriticDensity', ...
               'somaArea', ...
               'dendriticField', ...
               'biStratificationDistance'}};

featSet2 = { 'DD-SA-FD-BA', ...
             { 'dendriticDensity', ...
               'somaArea', ...
               'fractalDimensionBoxCounting', ...
               'meanBranchAngle'}};

featSet3 = { 'DD-SA-FD-DF', ...
             { 'dendriticDensity', ...
               'somaArea', ...
               'fractalDimensionBoxCounting', ...
               'dendriticField'}};

featSet4 = { 'DD-SA-TDL-TSL', ...
             { 'dendriticDensity', ...
               'somaArea', ...
               'totalDendriticLength', ...
               'meanTerminalSegmentLength'}};

featSets = {featSetAll,featSet1,featSet2,featSet3,featSet4};
    
for i = 1:numel(featSets)

  setName = featSets{i}{1};
  feats = featSets{i}{2};
  r.setFeatureMat(feats);

  [kBestAll{i},clusterID{i}] = r.optimizeBlindClusterNumber(2:11);

  fName = sprintf('FIGS/Silhouette-for-feature-set-%s.pdf', setName);
  
  saveas(gcf,fName,'pdf')
  
end