r = RGCclass(0); r.lazyLoad();

useFeatures = { 'densityOfBranchPoints', ...
                'dendriticField', ...
                'somaArea', ...
                'fractalDimensionBoxCounting', ...
                'meanTerminalSegmentLength' };

r.setFeatureMat(useFeatures)

r.predictionPosteriorProbabilitiesLeaveOneOut();
